# service
apiVersion: v1
kind: Service
metadata:
  name: SpringHello-service
  namespace: default
spec:
  selector:
    app: SpringHello
type: NodePort
ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080